name: Update Repo List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # ប្រើ v4 ធម្មតា

      - name: Update README with Repositories
        uses: gautamkrishnar/blog-post-workflow@master # ប្តូរពី @v1.0.0 មក @master វិញ
        with:
          feed_list: "https://github.com/chanrachory.atom"
