name: Update Repo List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # បំបាត់ Warning រឿង Node.js
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with Repositories
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "blog-posts" # កំណត់ឱ្យត្រូវនឹង Tag ក្នុង README
          feed_list: "https://github.com/chanrachory.atom"
